apiVersion: apps/v1
kind: Deployment
metadata:
  name: third-app
  labels:
    app: third-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: third-app
  template:
    metadata:
      labels:
        app: third-app
    spec:
      containers:
        - name: web
          image: nginx:1.25
          ports:
            - containerPort: 80
